### ISSUE TITLE
lunarvim is dead... we offer you a new home :D

### ISSUE THREAD

**Issue by luxus** [crisidev/lvim#2]
Hi
i remember you from 1 1/2 years ago when uzaaft and i still using abzcoding's config .. i found you by accident, after reading about the latest mason issue with nvim nightly and saw your profile pic :D
if you search for a new config we can recommend www.astronvim.com , many other lunarvim refugees are there

**Comment by crisidev** [comment]
Hey, nice to meet you again.. I thought about moving to astrovim many times, but I never found the time to work on migrating my config to it. I will probably have some time in May and I will try..

**Comment by luxus** [comment]
sure join our discord, discord.astronvim.com i knew the lvim config von abzcoding by heart.. we can help to migrate for sure .. see you maybe in may :D

**Comment by luxus** [comment]
ah and we have excellent rust support btw :)
https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/pack/rust

**Comment by crisidev** [comment]
I eventually moved to a LazyVim based config: https://github.com/crisidev/lazyvim/tree/main

More info https://lmno.lol/crisidev/lunarvim-lazyvim
